apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: g9mh7386w-python 
  janus-idp.io/tekton: g9mh7386w-python
  backstage.io/kubernetes-id: g9mh7386w-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: g9mh7386w-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  